### PR TITLE
partial fix for #33

### PR DESCRIPTION
**Pull request by ErichBSchulz**
@eileenmcnaughton this should unblock you on #33 

this was a bit more occult than I expected but looks like the get method creates a few instances of action object and the check permission flag wasn't getting passed down

### CODE REVIEW

**Comment by colemanw** [comment]
I have a couple questions on this one:

- What effect is checkPermissions having on the getActions and getFields actions? I'm surprised it has any.
- If it's absolutely necessary to set them to false, why not do it from the calling function?

But I suspect the real fix is to ensure that these actions function correctly even with checkPermissions = true.

**Comment by ErichBSchulz** [comment]
so I discovered the reason for the issue reported at #33, the `Get` action is creating a `GetFields` action and not passing the check fields flag

arguably the change to `GetActions` is not required

I'll need to do further homework on permissions and need a generalisable permission checking framework...

I was hoping to duck the ACL issue for a bit till I [am clearer about how to do it](http://civicrm.stackexchange.com/questions/17063/how-to-spoof-users-to-unit-test-acl-logic)

**Comment by eileenmcnaughton** [comment]
@ErichBSchulz I think there is a good permission checking framework - I just couldn't make sense of it when I looked.

**Comment by colemanw** [comment]
I believe this is superseded.

**Comment by ErichBSchulz** [comment]
I agree we can close this. Was reopening accidental @colemanw or was there something you wanted to discuss ?

**Pull request closed without merging**
